services:

  mysql:
    image: mysql:5.7
    container_name: mysql_jasperserver
    environment:
      MYSQL_ROOT_PASSWORD: "No$crash2025$"
      MYSQL_DATABASE: jasperserver
    volumes:
      - ./datadir:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pNo$crash2025$"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  jasperserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        JS_VERSION: 8.2.0
    container_name: jasperserver
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql_jasperserver
      DB_PORT: 3306
      DB_NAME: jasperserver
      DB_USER: root
      DB_PASSWORD: "No$crash2025$"
      TZ: UTC
    volumes:
      - ./jasperserver-import:/jasperserver-import
    networks:
      - default
      - fvnetwork
    restart: unless-stopped

networks:
  fvnetwork:
    external: true
